version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: quizdb
      POSTGRES_USER: quizuser
      POSTGRES_PASSWORD: quizdbpass

    ports:
      - 5432:5432
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

volumes:
  dbdata: